### PR TITLE
Added support for dotnet7 and upgraded NuGet packages.

### PR DESCRIPTION
**Pull request by chrisbbe**

### CODE REVIEW

**Comment by tillig** [comment]
Is there something we'd be gaining or fixing by adding the `net7.0` target here that folks don't get by using `net7.0` in the consuming projects? Especially considering core Autofac doing the real work doesn't target `net7.0`? I'm trying to understand the goal of this PR.

**Comment by chrisbbe** [comment]
Hi,

In my solution, after upgrading target framework to net7.0 and all Microsoft.* pakages to 7.0.0, I got a runtime exception where Microsoft.Bcl.AsyncInterfaces.dll version 6 could not be loaded when invoking Autofac. I guess the reason is that this library has an transient dependency on Microsoft.Bcl.AsyncInterfaces version 6 through package Microsoft.Extensions.DependencyInjection.Abstractions.

**Comment by tillig** [comment]
If you add a direct reference to Microsoft.Extensions.DependencyInjection 7.0.0 from your project does it go away? It should override the transient.

**Comment by chrisbbe** [comment]
I tried to add a direct reference to Microsoft.Bcl.AsyncInterface version 6 in the project, since it complained about that version. That worked for that project, but the missing DLL error showed up in other projects as well, at that point I reverted my dotnet 7 attempt.

**Comment by tillig** [comment]
If your theory is about Microsoft.Extensions.DependencyInjection being the thing that needs the reference, add 7.0.0 of that.

**Comment by chrisbbe** [comment]
Ok. If this PR is not accepted, when will this library be released with Autofac 6.5.0 ?

**Comment by tillig** [comment]
As noted in the docs [we don't release updates for the sake of updating](https://autofac.readthedocs.io/en/latest/faq/binding-redirect.html). If you want the latest Autofac core you can update your consuming projects.

**Comment by tillig** [comment]
Honestly, what will likely happen is we'll get core Autofac updated to net7 first (if it looks like that will help anything) and then propagate that through to dependent libraries. If core Autofac is net7 then it'd make sense to have this library also target net7 for whatever benefit to propagate out. I've not seen any concrete benefit to net7 specifically for core Autofac, but perhaps this AsyncInterfaces thing is confusing enough to require it.

Do you have some repro steps to see the issue you mentioned? Just create a new net7 console app and reference Autofac core? Something else?

**Pull request closed without merging**
