### PR TITLE
NET6 and IServiceProviderIsService support.

### PR DESCRIPTION
**Pull request by alistairjevans**
Raising a PR to bring this in now the builds are passing, and .NET 6 Preview 6 has been released with `IServiceProviderIsService` available.

I've made `AutofacServiceProvider` a partial class, and put the .NET 6 specific service on a partial in it's own file. Seemed like the cleanest way to add it.

All the new specific tests added by the dotnet team that validate this new behaviour are passing.

### CODE REVIEW

**Comment by tillig** [comment]
I figured out the problem with VS Code - OmniSharp only looks at the _first item in `TargetFrameworks`_ and generates issues and Intellisense based on that. I've moved the .NET 6 framework (and conditional references) to be encountered first in the projects and it's resolved all the weird "error being displayed but it compiles just fine" problems.

**Review by tillig — APPROVED** [review]
🍇

**Comment by tillig** [comment]
Since this seems to be high visibility would it be worth putting a beta out on NuGet for folks to try?

**Comment by alistairjevans** [comment]
Seems like a good idea.

Assuming you mean pushing [7.2.0-develop-00520](https://www.myget.org/feed/autofac/package/nuget/Autofac.Extensions.DependencyInjection/7.2.0-develop-00520) from MyGet to NuGet as 7.2.0-preview.1 or something?

**Comment by tillig** [comment]
Exactly that. I can take care of it later if you don't have time, either way.

**Comment by alistairjevans** [comment]
I'll push it later, should only take a minute. I'll raise a GitHub preview release for it as well.

**Comment by alistairjevans** [comment]
Nuget package pushed, I'll post on that original runtime thread that it's available.

**Pull request merged**
