### PR TITLE
Changed project reference to released Autofac 5.0

### PR DESCRIPTION
**Pull request by alistairjevans**
5.0 reference change made.

### CODE REVIEW

**Comment by alistairjevans** [comment]
Had a thought; does the integration package need bumping to 6.0 because of the Autofac major reference change?

**Comment by tillig** [comment]
Does it _only_ work with 5.0+ or _could_ it still work with 4.0? My brain is mush trying to keep everything straight.

Ideally taking this package wouldn't necessarily require an update to core Autofac unless we're doing something with it, like using an interface that changed.

If we have to take the update... man, this is a big semantic version hole right here. I was never clear on how dependency updates change the semver.

It might be worth the major version bump because we're forcing what could be breaking changes onto the client vis-a-vis core Autofac.

However... if it doesn't require Autofac 5 to function do we need to even make a release?

**Comment by tillig** [comment]
Oh, just found it - it's the IAsyncDisposable support that forces Autofac 5 here.

Let's go with a major version bump on this one to indicate that there are breaking changes forced on the client.

**Comment by alistairjevans** [comment]
Roger that, incoming.

**Comment by tillig** [comment]
Building the release now. I'll post it when it's done and pushed to NuGet. Thanks!

**Comment by alistairjevans** [comment]
Sweet; thought this would be a good one to get out quickly.

**Comment by tillig** [comment]
https://github.com/autofac/Autofac.Extensions.DependencyInjection/releases/tag/v6.0.0

**Pull request merged**
