### PR TITLE
feat: add support for .NET 5

### PR DESCRIPTION
**Pull request by alsami**
* Add explicit support for TFM `net5.0`
* Add additional framework 3.1.406
* Add TFM `net5.0` to test project as well
* Update test dependencies
* Update build scripts and raise version to 7.2
* Enable deterministic build for CI

### CODE REVIEW

**Comment by alsami** [comment]
Hibernating until official release ... will keep on updating when ever there's a new preview.

**Comment by alsami** [comment]
@tillig @alexmg @alistairjevans just noticed that this is still open... In the meanwhile plenty has changed for main Autofac including the TFMs we use.

I'd think to do the same here. What do you guys think:

* Basically support and add TFMs `netstandard2.0`, `netstandard2.1` and `net5.0`
* Include higher versions of `Microsoft.Extensions.DependencyInjection` based on TFM
* Adjust test to be executed against several frameworks

**Comment by tillig** [comment]
I'm not sure we need to have different Microsoft.Extensions.DependencyInjection per framework. The latest release still only targets `netstandard2.0` and `net461`.  I think maybe just adding `net5.0` here and calling it a day is all that's really needed.

**Comment by alsami** [comment]
> I'm not sure we need to have different Microsoft.Extensions.DependencyInjection per framework. The latest release still only targets `netstandard2.0` and `net461`. I think maybe just adding `net5.0` here and calling it a day is all that's really needed.

Sounds fine to me. What about running the test against multiple frameworks, do we desire that for this repository as well?

**Comment by tillig** [comment]
I'm fine if we want to run the tests against multiple frameworks. Couldn't hurt.

**Comment by tillig** [comment]
It seems like there are a few sqaush/push iterations to get through the build going on, which is fine, but I'm going to unsubscribe from it until it's ready to go so my email isn't getting flooded.

**Comment by alsami** [comment]
> It seems like there are a few sqaush/push iterations to get through the build going on, which is fine, but I'm going to unsubscribe from it until it's ready to go so my email isn't getting flooded.

Damn, tried to be quick. Done now, please review when you've got the time.

**Review by tillig — APPROVED** [review]
🎉 🎉 🎉

**Pull request merged**
