### PR TITLE
Add optional container-level `IServiceProvider` and `IServiceScopeFactory`

### PR DESCRIPTION
**Pull request by marcrocny**
Added implementations of `IServiceProvider` and `IServiceScopeFactory` that explicitly depend on and return `IContainer`: `AutofacContainerServiceProvider` and `AutofacContainerServiceScopeFactory`.  For `GetService()` on the former, when asked for an `IServiceProvider`, returns itself; for an `IServiceScopeFactory`, returns `AutofacContainerServiceScopeFactory(container)` ; anything else it resolves from the container. `CreateScope()` on the latter returns `AutofacServiceScope(container.BeginLifetimeScope())`.  

After that, it falls back to the implementations wired up in `AutofacRegistration.Populate()`.

`AutofacContainerServiceProvider` is intended to serve as the application container when necessary, and I added the tests as such.  **Not sure if there are other areas that need to be tested, this would be my primary concern.** I did not change the logic behind `AutofacServiceProviderFactory` in case there were other concerns--though it appears only to break the test that explicitly checks the return type of `CreateServiceProvider(...)`.

## For Multitenancy

This is a partial solution to issue #1.  The problem (or one way to look at it) is that the current implementations of [`IServiceProvider`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceProvider.cs) and [`IServiceScopeFactory`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceScopeFactory.cs) work otherwise, but are a tad too abstract for multitenancy.  Resolving them from `IContainer` (in the two implementations that I know of, `Container` and `MultitenantContainer`) *does not* return a reference to the container itself, but instead to the root lifetime scope.  That works when using `Container`, but breaks when using `MultitenantContainer` *because there is no root lifetime scope*. Or rather, no single root lifetime scope: there are as many as there are tenants, plus one for the default tenant.  Or rather again, there is a *real* root lifetime scope inside `MultitenantContainer.ApplicationContainer`, but that takes you outside the realm of multitenancy.

Even setting the application container to `new AutofacServiceProvider(container)` in `Startup.ConfigureServices` doesn't help because dependencies on `IServiceScopeFactory` resolved from `AutofacServiceProvider` will get the root/default lifetime scope, not the container.

This breaks multitenancy, because [`RequestServicesContainerMiddleware`](https://github.com/aspnet/Hosting/blob/b6a3fee08869cd9ac9d266b15b4eb7de205199ed/src/Microsoft.AspNetCore.Hosting/Internal/RequestServicesContainerMiddleware.cs) takes an `IServiceScopeFactory` directly in its constructor, and uses that to set the provider for a given session.  For multitenancy, this must be the container itself, otherwise it will only resolve against the default tenant scope.

With this solution, `RequestServicesContainerMiddleware` receives a container-based scope-factory, which gives space to resolve the tenant as needed.

### CODE REVIEW

**Comment by tillig** [comment]
Just working it through in my head here, so I may repeat stuff you said but in different words.

The root of the problem, if I understand it right, is that the `RequestServicesMiddleware` needs an `IServiceScopeFactory` during construction. That `IServiceScopeFactory` is constructed once per _application lifetime_ (e.g., it's a singleton) rather than once _per request_. The way we currently deal with the `IServiceScopeFactory` is that we _resolve_ it from the `AutofacServiceProvider` [using `Resolve`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/6af0cd9da65101ab749165261b5275fc69263ff1/src/Autofac.Extensions.DependencyInjection/AutofacServiceProvider.cs#L69) rather than "newing it up" based on the current lifetime scope.

Since it's resolved, that causes tenant identification to run and create a tenant-specific lifetime scope and _then_ resolve the `IServiceScopeFactory` - basing the service scope factory on the tenant lifetime rather than the container. Since it's already identified the tenant - too early in the pipeline - that "locks the tenant in" for the rest of the app lifetime.

If, instead of _resolving_ the scope factory, we manually _new up_ the factory around the current lifetime scope (or container) it won't force the tenant to be resolved until the request scope itself actually gets spawned.

SOOOO...

Here's stuff I'm thinking about:

- We [register `IServiceScopeFactory` and `IServiceProvider`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/6af0cd9da65101ab749165261b5275fc69263ff1/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L54) in the container. Having two different service providers or scope factories will mean you get two different results - based on whether you resolve directly from a lifetime scope or resolve from an `IServiceProvider`. That inconsistency isn't so good. Is there a way to change the registrations in `AutofacRegistration` to allow the behavior we want and ensure consistency at the same time?
- Alternatively, should we remove the registrations so you _can't_ resolve those things from the container and instead move _entirely_ to "knowing" about the MS DI types like `IServiceScopeFactory` inside `GetService`? Doing a `new` rather than a `Resolve<T>()` sounds like it's closer to the real answer.
- Is there any way to creatively use `Lazy<T>` in places to defer the creation of any service scope until it's actually used? (If so, would that even help? I doubt it, but like I said I'm still kinda working through this in my head.)
- Is there a way we can add to the multitenant container behavior that will make something like this easier? (Again, not really sure what that'd look like, and I doubt it, but still working it through.)
- Would it be better to just bundle up [some custom Autofac multitenant-aware middleware](http://stackoverflow.com/questions/38940241/autofac-multitenant-in-an-aspnet-core-application-does-not-seem-to-resolve-tenan/38960122#38960122) to address this very specific problem and wrap the setup in convenient extension methods? That might be heavy-handed, but at the same time, this is sort of an edge case comparatively speaking.

I'm okay with changing the internal behavior of things as long as the tests still pass. I think the ability to resolve an `IServiceProvider` from the container is interesting but I can also see that mixing DI (switching _in code_ from Autofac to MS to Autofac to MS) is sort of what's causing this weird challenge. I'm not sure anything resolved _from a lifetime scope_ rather than _from an `IServiceScope`_ should need an `IServiceProvider`.

I'm curious about what @alexmg thinks. He's spent some time in here and may have an idea I haven't come up with yet.

**Comment by marcrocny** [comment]
Thanks for the feedback!  I think your problem statement hit the main points. Nothing wrong with restating to aid understanding.

I agree that @alexmg 's input is paramount in this case.  He's lived this one, done it well and landed some nice ["brand placement"](<https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#replacing-the-default-services-container>) to boot, so this needs to keep working smoothly.  I liked that my solution was unobtrusive (tests pass, code minimally changed, use is optional) but at the same time fixed the problem.  I can understand your concerns about the introduction of inconsistency, though.

To each of your points:

* *Is there a way to change the registrations in  `AutofacRegistration` to allow the behavior we want and ensure consistency at the same time?* With pure registration, I don't think it is possible.  Alex's solution for providing MS DI abstractions was quite elegant: just provide light wrappers around `IComponentContext` and `ILifetimeScope` (themselves the same thing) *et voila* you've provided everything MS DI asks for.  But, since you can't resolve an `IContainer`, you can't get to where you need to go (for multitenancy) without `new`.  But it's a well-contained use of `new`, I think.
* *Alternatively, should we remove the registrations...?* That's an interesting idea, especially for `IServiceProvider`.  Alex's solution allows for resolving an `IServiceProvider`, but I don't know if that is strictly necessary--I think only `IServiceScope` is used after that.  I'm up for investigating that.  If we don't have to allow resolution, (the MS tests don't require it) maybe better *not to resolve*. Sort of a YAGNI variant... MS-AGNI?
* *creatively use  `Lazy<T>`...?* I thought about that, but I couldn't figure a way to get `Lazy<T>` (or `Func<T>`) to "wait" for tenant ID.  Admittedly, once I figured a way to `new` my way out of the loop I was stuck in I stopped banging my head against that one.
* *add to the multitenant container behavior...?* I thought about that, too. The key is "add to" and not "change".  As far as I could figure, it would require changing the way that MTC behaves in respect to some resolutions (somehow making "root" resolutions of `IComponentContext` and `ILifetimeScope` be "pre-tenant-binding") that would introduce a major breaking change--really a breaking way-of-thinking-about-MTC--that was far more disruptive.
* *custom Autofac multitenant-aware middleware...?*  If the solution takes us in the direction of requiring yet-another-autofac package for MTC in ASP.NET Core, because for some reason the ideas in this PR are anathema, I'd rather take the "container" versions of serivce-provider and scope-factory and put them in their own package.  I'm actually doing that for a project now, defining them in application code. That SO solution was masterful and I wouldn't have gotten to this solution without the research you did there.  But even packaged, it's a little "brute-force" for me.

I'm going to experiment with making this "more consistent," and see whether resolving `IServiceProvider` is really a requirement.

**Comment by marcrocny** [comment]
I did a quick "experiment" of removing the registration for `IServiceFactory` and fixing what breaks.  I ended up with a single failing test in the MS Specs that relies on [`ClassWithNestedReferencesToProvider`](https://github.com/aspnet/DependencyInjection/blob/771cb483bc5df120a0fab84ec914a7ac7de21448/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/Fakes/ClassWithNestedReferencesToProvider.cs).  It's not direct, but the inclusion implies the requirement to not just have and use `IServiceProvider` on the current `IServiceScope`, but to also be able to inject it where needed.  Looks like that is a requirement.

Hopefully the removal of the superfluous `AutofacContainerServiceScopeFactory` makes the PR more palatable from a "consistency" standpoint.

**Comment by alexmg** [comment]
I've started reading through this one but it's going to take me a little time to get up to speed. I might need to fire up the sample project to get my head around the order of events properly.

As a side note, `Container` and `LifetimeScope` have always implemented `IServiceProvider`, which has been around since .NET 1.0. While the interface was never added as an explicit registration, and isn't inherited by `IComponentContext`, `ILifetimeScope` or `IContainer`, you have always been able to cast the implementation types to `IServiceProvider`. This might be something worth keeping in mind while looking for a solution.

**Comment by tillig** [comment]
After talking it over with @alexmg I think it'd be good to keep the Autofac.Extensions.DependencyInjection adapter really as thin as possible. As soon as we start doing too much in the way of special casing around whether it's a root container or lifetime scope; whether you're resolving a specific type; and so on; it's going to be more difficult to maintain and generally more fragile.

We do appreciate the work that was done here and the ideas being put forward. However, given the workaround posted in StackOverflow would likely fit nicely in [an Autofac.AspNetCore package](https://github.com/autofac/Autofac.AspNetCore) we'll probably look to just add a nice extension method like `containerBuilder.UseAutofacRequestServices()` where we can add a post-build callback and automatically attach request services and a custom middleware right to the list of startup filters. Or, you know, something very akin to that. This way it'll be something that...

- Doesn't change the adapter behavior.
- Is something you can opt into if you need it but isn't required.
- Should be fairly simple to maintain and shouldn't change often.

Again, though, thanks. PRs and thoughtful discussion is really helpful when trying to solve issues.

**Comment by marcrocny** [comment]
Respectfully, I'm disappointed.  I thought this change addressed an apparent edge case in an intuitive (or at least non-breaking) way and  without adding any real "thickness."  It basically packaged a workaround that doesn't require middleware, but unfortunately requires the reproduction of classes that are "internal" to induce the minor changes in this PR.  Instead, you'll be adding a template for the much thicker middleware based workaround to yet *another* package to be referenced.  I don't see now that is less thick.

**Pull request closed without merging**
